name: docker build
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Get version from package.json
        id: extractver
        run: echo "::set-output name=version::$(jq '.version' package.json | sed 's/"//')"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/avafloww/thinwiki:latest, ghcr.io/avafloww/thinwiki:${{ steps.extractver.outputs.version }}
